
# Uncomment the next line to define a global platform for your project

target 'Study_RxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Study_RxSwift
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'
  pod 'Kingfisher'
  pod 'Hue'
  pod 'SwiftyJSON'
  pod 'Gifu'
  pod 'RxTimelane', '1.0.9'
  pod 'Alamofire', '4.9.1'
  pod 'RealmSwift', '5.1.0'
  pod 'RxRealm', '3.0.0'
  pod 'Unbox', '4.0.0'
  pod 'Then', '2.7.0'
  pod 'Reachability', '3.2.0'
  pod 'RxRealmDataSources', '0.3.0'
  pod 'RxDataSources', '4.0.1'
  
  target 'Study_RxSwiftTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'Nimble'
    pod 'RxNimble'
    pod 'OHHTTPStubs/Swift'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end